
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: jon@2386912
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
#      show_sql : true
      format_sql: true
      ddl-auto: create

  devtools:
    livereroad:
      enable: true
    freemarker:
      cache: false
    add-properties: true

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type: trace

